export default {
  app: { title: 'AI Novel Game', loading: 'Loading...' },
  home: { title: 'My Worlds', createWorld: 'Create New World', noWorlds: 'No worlds yet', noWorldsHint: 'Click the button above to begin', settings: 'Settings', enter: 'Enter', delete: 'Delete', confirmDelete: 'Are you sure you want to delete this world?' },
  settings: { title: 'Settings', back: '← Back', llmConfigs: 'LLM Configurations', imageConfigs: 'Image Configurations', voiceConfigs: 'Voice Configurations', imageFrequency: 'Image Trigger Frequency', add: '+ Add', noConfigs: 'No configurations yet. Click "+ Add" to create one.', ping: 'Ping', active: 'Active', edit: 'Edit', del: 'Del', save: 'Save Settings', cancel: 'Cancel', newConfig: 'New Configuration', editConfig: 'Edit Configuration', name: 'Name', nameRequired: 'Name (required)', provider: 'Provider', model: 'Model', modelName: 'Model Name', apiKey: 'API Key', apiBaseUrl: 'API Base URL', apiBaseUrlHint: '(optional, include /v1)', size: 'Size', quality: 'Quality', voice: 'Voice', speed: 'Speed', autoPlayVoice: 'Auto-Play Voice', autoPlayVoiceDesc: 'Automatically read character dialogue aloud when voice API is configured', language: 'Language', conservative: 'Conservative (scene changes only)', standard: 'Standard (scene + major actions)', rich: 'Rich (more triggers)', testSuccess: 'Connection OK', testFail: 'Connection FAIL', saveWorldSettings: 'Save World Settings', nameWorldviewRequired: 'Name and worldview are required', llmTab: 'LLM', imageTab: 'Image', voiceTab: 'Voice' },
  worldCreate: { title: 'Create New World', back: '← Back', worldSettings: 'World Settings', worldName: 'World Name', worldNamePlaceholder: 'e.g. Land of Sword and Magic', worldview: 'Worldview', worldviewPlaceholder: 'Describe the background, history, systems...', rules: 'Rules', rulesPlaceholder: 'Laws and limitations of this world', systemPrompt: 'System Prompt', systemPromptPlaceholder: 'Additional system instructions for AI', initialScene: 'Initial Scene', initialScenePlaceholder: 'Scene description when the game starts', playerSettings: 'Player Character', playerName: 'Character Name', playerNamePlaceholder: 'Your character name', gender: 'Gender', genderPlaceholder: 'Male / Female / Other', age: 'Age', appearance: 'Appearance', appearancePlaceholder: 'Height, hair color, clothing style...', personality: 'Personality', personalityPlaceholder: 'Core traits, values, speaking style...', extraPrompt: 'Extra Prompt', extraPromptPlaceholder: 'Special requirements for AI generation', importantChars: 'Important Characters', importantCharsOptional: '(optional)', addChar: '+ Add Character', noCharsYet: 'No important characters added yet. AI can fill in during gameplay.', charNumber: 'Character #', createBtn: 'Create World and Begin Adventure', creating: 'Creating...', fillRequired: 'Name and worldview are required', fillPlayerName: 'Player character name is required', createFailed: 'Creation failed', charModalTitle: 'Add Character', nameRequired: 'Name', genderRequired: 'Gender', ageRequired: 'Age', charImage: 'Character Image', charImageOptional: '(optional)', uploadImage: 'Upload Image', changeImage: 'Change Image', confirmAdd: 'Confirm Add', appearanceDesc: 'Appearance Description', fillCharRequired: 'Please fill in name, gender, and age' },
  game: { send: 'Send', inputPlaceholder: 'Type action or dialogue...', freePlaceholder: 'Describe your action... or (talking to XXX) to initiate dialogue', processing: 'AI is thinking...', aiError: 'AI response failed', drawing: 'Drawing...', noScene: 'No scene illustration yet', generateScene: 'Click 🎲 above to generate', sceneCharacters: 'Characters present', free: 'Free', talk: 'Talk', gmPanel: 'GM Panel', gmPlaceholder: 'GM command...', gmHint: 'Use this panel to directly modify world settings, characters, and rules', worldSettings: 'World Settings', newCharRequest: 'AI suggests new character', confirmChar: 'Confirm Add', skipChar: 'Skip', newCharFailed: 'Add character failed', delConfirm: 'Delete this message?', rollbackConfirm: 'Delete all messages after this point?', readAloud: 'Read aloud', stopRead: 'Stop' },
  storyLog: { title: 'Story Log', back: '← Back', typeNarration: 'Narration', typeAction: 'Action', typeMonologue: 'Monologue', typeDialogue: 'Dialogue', noEntries: 'No story entries yet' },
  worldSettingsModal: { worldSettings: 'Settings', characters: 'Characters', saveWorld: 'Save World Settings', saving: 'Saving...', saveFailed: 'Save failed', editChar: 'Edit Character', backToList: '← Back to list', deleteCharConfirm: 'Delete this character?', deleteFailed: 'Delete failed' },
  common: { save: 'Save', cancel: 'Cancel', confirm: 'Confirm', delete: 'Delete', edit: 'Edit', close: 'Close', back: 'Back', loading: 'Loading...', error: 'Error', unknownError: 'Unknown error' }
}