export default {
  app: { title: 'AI Novel Game', loading: '載入中...' },
  home: { title: '我的世界', createWorld: '建立新世界', noWorlds: '尚未建立任何世界', noWorldsHint: '點擊上方按鈕開始冒險', settings: '設定', enter: '進入', delete: '刪除', confirmDelete: '確定要刪除這個世界嗎？' },
  settings: { title: '設定', back: '← 返回', llmConfigs: 'LLM 設定', imageConfigs: '圖片生成設定', voiceConfigs: '語音設定', imageFrequency: '圖片觸發頻率', add: '+ 新增', noConfigs: '尚無設定，點擊「+ 新增」建立', ping: '測試', active: '啟用', edit: '編輯', del: '刪除', save: '儲存設定', cancel: '取消', newConfig: '新增設定', editConfig: '編輯設定', name: '名稱', nameRequired: '名稱（必填）', provider: 'Provider', model: '模型', modelName: '模型名稱', apiKey: 'API Key', apiBaseUrl: 'API Base URL', apiBaseUrlHint: '(可選，需包含 /v1)', size: '尺寸', quality: '品質', voice: '語音', speed: '語速', autoPlayVoice: '自動朗讀', autoPlayVoiceDesc: '有接入語音 API 時，角色對話自動播放音頻', language: '語言', conservative: '保守（僅場景變化）', standard: '標準（場景 + 主要行動）', rich: '豐富（更多觸發）', testSuccess: '連線成功', testFail: '連線失敗', saveWorldSettings: '儲存世界設定', nameWorldviewRequired: '請至少填寫名稱和世界觀', llmTab: 'LLM', imageTab: '圖片', voiceTab: '語音' },
  worldCreate: { title: '建立新世界', back: '← 返回', worldSettings: '世界設定', worldName: '世界名稱', worldNamePlaceholder: '例如：劍與魔法的大陸', worldview: '世界觀', worldviewPlaceholder: '描述這個世界的背景、歷史、體系...', rules: '規則', rulesPlaceholder: '世界的法則與限制', systemPrompt: '系統 Prompt', systemPromptPlaceholder: '給 AI 的額外系統指令', initialScene: '初始場景', initialScenePlaceholder: '遊戲開始時的場景描述', playerSettings: '主角設定', playerName: '主角名稱', playerNamePlaceholder: '你的角色名稱', gender: '性別', genderPlaceholder: '男 / 女 / 其他', age: '年齡', appearance: '外觀', appearancePlaceholder: '身高、髮色、服裝風格等', personality: '性格', personalityPlaceholder: '核心性格特徵、價值觀、說話風格...', extraPrompt: '額外 Prompt', extraPromptPlaceholder: '對 AI 生成此角色時的特別要求', importantChars: '重要角色', importantCharsOptional: '(可選)', addChar: '+ 新增角色', noCharsYet: '尚未添加重要角色，可由 AI 在遊戲中補全', charNumber: '角色 #', createBtn: '建立世界並開始冒險', creating: '建立中...', fillRequired: '請至少填寫世界名稱和世界觀', fillPlayerName: '請填寫主角名稱', createFailed: '建立失敗', charModalTitle: '新增角色', nameRequired: '名稱', genderRequired: '性別', ageRequired: '年齡', charImage: '角色圖片', charImageOptional: '(可選)', uploadImage: '上傳圖片', changeImage: '更換圖片', confirmAdd: '確認添加', appearanceDesc: '外觀描述', fillCharRequired: '請填寫名稱、性別和年齡' },
  game: { send: '發送', inputPlaceholder: '輸入動作或對話...', freePlaceholder: '描述你的行動... 或 (正與XXX說話) 發起對話', processing: 'AI 思考中...', aiError: 'AI 回應失敗', drawing: '繪製中...', noScene: '尚無場景插畫', generateScene: '點擊上方 🎲 生成', sceneCharacters: '在場角色', free: '自由', talk: '對話', gmPanel: 'GM 面板', gmPlaceholder: 'GM 指令...', gmHint: '使用此面板直接修改世界設定、角色和規則', worldSettings: '世界設定', newCharRequest: 'AI 建議新增角色', confirmChar: '確認新增', skipChar: '略過', newCharFailed: '新增角色失敗', delConfirm: '確定要刪除此訊息嗎？', rollbackConfirm: '確定要刪除此訊息之後的所有對話嗎？', readAloud: '朗讀', stopRead: '停止' },
  storyLog: { title: '故事日誌', back: '← 返回', typeNarration: '敘述', typeAction: '動作', typeMonologue: '獨白', typeDialogue: '對話', noEntries: '尚無故事記錄' },
  worldSettingsModal: { worldSettings: '設定', characters: '角色', saveWorld: '儲存世界設定', saving: '儲存中...', saveFailed: '儲存失敗', editChar: '編輯角色', backToList: '← 返回列表', deleteCharConfirm: '確定要刪除此角色嗎？', deleteFailed: '刪除失敗' },
  common: { save: '儲存', cancel: '取消', confirm: '確認', delete: '刪除', edit: '編輯', close: '關閉', back: '返回', loading: '載入中...', error: '錯誤', unknownError: '未知錯誤' }
}